from . import res_users
from . import product_template
from . import account_payment_register
from . import sale_order
from . import sale_order_line
from . import custom_input_wizard
from . import stock_picking
from . import account_move
from . import purchase_order
from . import purchase_order_line
from . import utils